# Site settings
title: Introduction to Robotics (EECS 4342)  Lab Manual
email: ngans@utdallas.edu
description: "Lab materials and codebase for UT Dallas' class EECS 4342: Introduction to Robotics."
baseurl: ""
url: "http://SeRViCE-Lab.github.io"
twitter_username: patmeansnoble
github_username: eecs4342
timezone: America/Chicago
gems:
    - jekyll-redirect-from
# Build settings
markdown: redcarpet
permalink: pretty
