# Site settings
title: Introduction to Robotics(Lab Manual)- EECS 4342
email: ngans@utdallas.edu
description: "Lab materials and codebase for UT Dallas' class EECS 4342: Introduction to Robotics."
baseurl: ""
url: "http://eecs4342.github.io.github.io"
twitter_username: @patmeansnoble
github_username:  SeRViCE-Lab
timezone: America/Chicago
gems:
    - jekyll-redirect-from
# Build settings
markdown: redcarpet
permalink: pretty